name: Compilar y Subir DatosEscalamiento.exe

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-release:
    runs-on: windows-latest

    steps:
    - name: Clonar el código local
      uses: actions/checkout@v4

    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Instalar librerías y PyInstaller
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements.txt

    - name: Compilar a .exe
      run: |
        # Ejecutamos con 'python -m PyInstaller' para garantizar el mismo entorno de pip
        # Usamos '--collect-all customtkinter' para empacar los temas y fuentes
        python -m PyInstaller --noconfirm --onefile --windowed --name "DatosEscalamiento" --collect-all customtkinter Datos_de_Escalamiento.py

    - name: Subir archivo a Ejecutables
      env:
        GH_TOKEN: ${{ secrets.TOKEN_EJECUTABLES }}
      run: |
        # Sube el ejecutable al repositorio central de Ejecutables en el tag 'produccion'
        gh release upload Produccion dist/DatosEscalamiento.exe --repo idwin1/Ejecutables --clobber
